version: "3.9"

services:
  nello-db:
    image: postgres:15
    container_name: ${PG_DB_CONTAINER_NAME}
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - nello-network

  nello-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${SERVER_NAME}
    restart: always
    depends_on:
      - nello-db
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:8080"
    networks:
      - nello-network

volumes:
  pgdata:

networks:
  nello-network:
    driver: bridge