version: "3.9"

services:
  trello-db:
    image: postgres:15
    container_name: ${PG_CONTAINER_NAME}
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    ports:
      - "${PG_PORT}:5432"  # host:container, host dùng 5434
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - trello-network
volumes:
  pgdata:

networks:
  trello-network:
    driver: bridge